// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.6
// source: sp_gm.proto

package game_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HEAD
type CSPkgHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CmdID          *uint32 `protobuf:"varint,1,req,name=CmdID" json:"CmdID,omitempty"`
	MsgSeqID       *uint32 `protobuf:"varint,2,req,name=MsgSeqID" json:"MsgSeqID,omitempty"`
	NotifyMsgSeqID *uint32 `protobuf:"varint,3,opt,name=NotifyMsgSeqID" json:"NotifyMsgSeqID,omitempty"`
	// 低 4 位表示加密类型 @see EnmEncryptType; 高 4 位表示压缩类型 @see EnmCompressType
	EncryptCompressType *uint32 `protobuf:"varint,4,opt,name=EncryptCompressType" json:"EncryptCompressType,omitempty"`
}

func (x *CSPkgHead) Reset() {
	*x = CSPkgHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sp_gm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CSPkgHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CSPkgHead) ProtoMessage() {}

func (x *CSPkgHead) ProtoReflect() protoreflect.Message {
	mi := &file_sp_gm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CSPkgHead.ProtoReflect.Descriptor instead.
func (*CSPkgHead) Descriptor() ([]byte, []int) {
	return file_sp_gm_proto_rawDescGZIP(), []int{0}
}

func (x *CSPkgHead) GetCmdID() uint32 {
	if x != nil && x.CmdID != nil {
		return *x.CmdID
	}
	return 0
}

func (x *CSPkgHead) GetMsgSeqID() uint32 {
	if x != nil && x.MsgSeqID != nil {
		return *x.MsgSeqID
	}
	return 0
}

func (x *CSPkgHead) GetNotifyMsgSeqID() uint32 {
	if x != nil && x.NotifyMsgSeqID != nil {
		return *x.NotifyMsgSeqID
	}
	return 0
}

func (x *CSPkgHead) GetEncryptCompressType() uint32 {
	if x != nil && x.EncryptCompressType != nil {
		return *x.EncryptCompressType
	}
	return 0
}

// BODY
type SPGMReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api      *string `protobuf:"bytes,1,req,name=Api" json:"Api,omitempty"`
	Data     *string `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	ServerID *int32  `protobuf:"varint,3,opt,name=ServerId" json:"ServerId,omitempty"`
}

func (x *SPGMReq) Reset() {
	*x = SPGMReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sp_gm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPGMReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPGMReq) ProtoMessage() {}

func (x *SPGMReq) ProtoReflect() protoreflect.Message {
	mi := &file_sp_gm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPGMReq.ProtoReflect.Descriptor instead.
func (*SPGMReq) Descriptor() ([]byte, []int) {
	return file_sp_gm_proto_rawDescGZIP(), []int{1}
}

func (x *SPGMReq) GetApi() string {
	if x != nil && x.Api != nil {
		return *x.Api
	}
	return ""
}

func (x *SPGMReq) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

func (x *SPGMReq) GetServerID() int32 {
	if x != nil && x.ServerID != nil {
		return *x.ServerID
	}
	return 0
}

// 返回
type SPGMRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Api    *string `protobuf:"bytes,1,req,name=Api" json:"Api,omitempty"`
	Data   *string `protobuf:"bytes,2,req,name=Data" json:"Data,omitempty"`
	Result *int32  `protobuf:"varint,3,opt,name=Result" json:"Result,omitempty"`
	ErrMsg *string `protobuf:"bytes,4,opt,name=ErrMsg" json:"ErrMsg,omitempty"`
}

func (x *SPGMRes) Reset() {
	*x = SPGMRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sp_gm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SPGMRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SPGMRes) ProtoMessage() {}

func (x *SPGMRes) ProtoReflect() protoreflect.Message {
	mi := &file_sp_gm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SPGMRes.ProtoReflect.Descriptor instead.
func (*SPGMRes) Descriptor() ([]byte, []int) {
	return file_sp_gm_proto_rawDescGZIP(), []int{2}
}

func (x *SPGMRes) GetApi() string {
	if x != nil && x.Api != nil {
		return *x.Api
	}
	return ""
}

func (x *SPGMRes) GetData() string {
	if x != nil && x.Data != nil {
		return *x.Data
	}
	return ""
}

func (x *SPGMRes) GetResult() int32 {
	if x != nil && x.Result != nil {
		return *x.Result
	}
	return 0
}

func (x *SPGMRes) GetErrMsg() string {
	if x != nil && x.ErrMsg != nil {
		return *x.ErrMsg
	}
	return ""
}

var File_sp_gm_proto protoreflect.FileDescriptor

var file_sp_gm_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x70, 0x5f, 0x67, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x22, 0x97, 0x01, 0x0a, 0x09, 0x43, 0x53, 0x50, 0x6b,
	0x67, 0x48, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x02, 0x28, 0x0d, 0x52, 0x05, 0x43, 0x6d, 0x64, 0x49, 0x44, 0x12, 0x1a, 0x0a, 0x08, 0x4d,
	0x73, 0x67, 0x53, 0x65, 0x71, 0x49, 0x44, 0x18, 0x02, 0x20, 0x02, 0x28, 0x0d, 0x52, 0x08, 0x4d,
	0x73, 0x67, 0x53, 0x65, 0x71, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66,
	0x79, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x71, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x0e, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79, 0x4d, 0x73, 0x67, 0x53, 0x65, 0x71, 0x49, 0x44, 0x12,
	0x30, 0x0a, 0x13, 0x45, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x13, 0x45, 0x6e,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x72, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70,
	0x65, 0x22, 0x4b, 0x0a, 0x07, 0x53, 0x50, 0x47, 0x4d, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x41, 0x70, 0x69, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x41, 0x70, 0x69, 0x12, 0x12,
	0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x49, 0x44, 0x22, 0x5f,
	0x0a, 0x07, 0x53, 0x50, 0x47, 0x4d, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x70, 0x69,
	0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x03, 0x41, 0x70, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x16, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73,
	0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x42,
	0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
}

var (
	file_sp_gm_proto_rawDescOnce sync.Once
	file_sp_gm_proto_rawDescData = file_sp_gm_proto_rawDesc
)

func file_sp_gm_proto_rawDescGZIP() []byte {
	file_sp_gm_proto_rawDescOnce.Do(func() {
		file_sp_gm_proto_rawDescData = protoimpl.X.CompressGZIP(file_sp_gm_proto_rawDescData)
	})
	return file_sp_gm_proto_rawDescData
}

var file_sp_gm_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_sp_gm_proto_goTypes = []interface{}{
	(*CSPkgHead)(nil), // 0: protobuf.CSPkgHead
	(*SPGMReq)(nil),   // 1: protobuf.SPGMReq
	(*SPGMRes)(nil),   // 2: protobuf.SPGMRes
}
var file_sp_gm_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sp_gm_proto_init() }
func file_sp_gm_proto_init() {
	if File_sp_gm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sp_gm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CSPkgHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sp_gm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPGMReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sp_gm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SPGMRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sp_gm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sp_gm_proto_goTypes,
		DependencyIndexes: file_sp_gm_proto_depIdxs,
		MessageInfos:      file_sp_gm_proto_msgTypes,
	}.Build()
	File_sp_gm_proto = out.File
	file_sp_gm_proto_rawDesc = nil
	file_sp_gm_proto_goTypes = nil
	file_sp_gm_proto_depIdxs = nil
}
